# Import Library's which will we use in this project

In [2]:
import numpy as np 
import pandas as pd 

# Import the NumPy and Pandas libraries for numerical computations and data manipulation.

In [3]:
from matplotlib import pyplot as plt
import seaborn as sns

# There are several libraries available in Python that help us visualize data. 
# These libraries make it easy to create charts, graphs, 
# and other visualizations for better data analysis and understanding.

In [4]:
from sqlalchemy import create_engine,text
import mysql.connector as mc

# There are several libraries in Python that help connect to a MySQL database, 
# making it easy to retrieve, insert, update, and manage data.

# Read the CSV File

This step loads the CSV (Comma-Separated Values) file into a Pandas DataFrame, 
allowing you to view, explore, clean, manipulate, 
and analyze the dataset efficiently.

In [4]:
df = pd.read_csv(r'E:\Real-Time Ferry Ticket Sales & Redemption Analytics for Toronto Island Park\data\Toronto Island Ferry Tickets(1).csv')

# Let's Start Analysis

In [5]:
# shape 
df.shape

(261538, 4)

In [6]:
# columns 
df.columns

Index(['_id', 'Timestamp', 'Redemption Count', 'Sales Count'], dtype='object')

In [7]:
# dtype 
df.dtypes

_id                  int64
Timestamp           object
Redemption Count     int64
Sales Count          int64
dtype: object

In [8]:
df.describe()

                 _id  Redemption Count    Sales Count
count  261538.000000     261538.000000  261538.000000
mean   130769.500000         48.885030      49.599106
std     75499.661689        104.549336      99.862285
min         1.000000          0.000000       0.000000
25%     65385.250000          3.000000       3.000000
50%    130769.500000         11.000000      13.000000
75%    196153.750000         40.000000      48.000000
max    261538.000000       7216.000000    7229.000000

In [17]:
df.head()

   _id            Timestamp  Redemption Count  Sales Count
0    1  2025-12-21T22:30:00                14           16
1    2  2025-12-21T22:15:00                 1            0
2    3  2025-12-21T22:00:00                 2            0
3    4  2025-12-21T21:30:00                11            1
4    5  2025-12-21T21:15:00                10            0

# Change Columns name and Case

In [9]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [12]:
df = df.rename(columns={'_id':'id'})

In [13]:
df.columns

Index(['id', 'timestamp', 'redemption_count', 'sales_count'], dtype='object')

# Change Datatypes

In [14]:
df.dtypes

id                   int64
timestamp           object
redemption_count     int64
sales_count          int64
dtype: object

In [15]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261538 entries, 0 to 261537
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                261538 non-null  int64
 1   timestamp         261538 non-null  datetime64[ns]
 2   redemption_count  261538 non-null  int64
 3   sales_count       261538 non-null  int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 8.0 MB

# Data Cleaning

* Check null values and duplicate values also check negative values

In [17]:
df.isnull().sum()

id                  0
timestamp           0
redemption_count    0
sales_count         0
dtype: int64

In [19]:
df.head(1)

   id           timestamp  redemption_count  sales_count
0   1 2025-12-21 22:30:00                14           16

In [18]:
df.duplicated().sum()

np.int64(0)

In [26]:
df[df[['sales_count','redemption_count']] < 0].any()

C:\Users\Mohd Noman\AppData\Local\Temp\ipykernel_10756\453948451.py:1: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  df[df[['sales_count','redemption_count']] < 0].any()

id                  False
timestamp           False
redemption_count    False
sales_count         False
dtype: bool

In [28]:
(df[['sales_count', 'redemption_count']] < 0).sum()

sales_count         0
redemption_count    0
dtype: int64

* there are no null values and zero duplicated values and zero negative values

# Feature Engineering

* create a new columns hours of days

In [42]:
df.head(1)

,id,timestamp,redemption_count,sales_count,hours,day_name,month_name,month,season,week_part
0,1,2025-12-21 22:30:00,14,16,22,Sunday,December,12,Winter,Weekend

In [31]:
df['hours'] = df['timestamp'].dt.hour

In [33]:
df['day_name'] = df['timestamp'].dt.day_name()

In [35]:
df['month_name'] = df['timestamp'].dt.month_name()

In [37]:
df['month'] = df['timestamp'].dt.month

In [39]:
df['season'] = df['month'].map(
    {
    1: "Winter",
    2: "Winter",
    3: "Spring",
    4: "Spring",
    5: "Spring",
    6: "Summer",
    7: "Summer",
    8: "Summer",
    9: "Fall",
    10: "Fall",
    11: "Fall",
    12: "Winter"
}
)

In [41]:
df['week_part'] = df['day_name'].map({
    'Monday': 'Weekday',
    'Tuesday': 'Weekday',
    'Wednesday': 'Weekday',
    'Thursday': 'Weekday',
    'Friday': 'Weekday',
    'Saturday': 'Weekend',
    'Sunday': 'Weekend'
})

In [59]:
df['gap'] = df['sales_count'] - df['redemption_count']

In [ ]:
df['day_period'] = df['hours'].map(
    {
    0: "Mid Night",
    1: "Mid Night",
    2: "Mid Night",
    3: "Mid Night",
    4: "Mid Night",

    5: "Early Morning",
    6: "Early Morning",
    7: "Early Morning",
    8: "Early Morning",

    9: "Morning",
    10: "Morning",
    11: "Morning",

    12: "Afternoon",
    13: "Afternoon",
    14: "Afternoon",
    15: "Afternoon",

    16: "Evening",
    17: "Evening",
    18: "Evening",

    19: "Night",
    20: "Night",
    21: "Night",

    22: "Late Night",
    23: "Late Night"
}
)

In [63]:
df.isnull().sum()

id                  0
timestamp           0
redemption_count    0
sales_count         0
hours               0
day_name            0
month_name          0
month               0
season              0
week_part           0
gap                 0
dtype: int64

In [62]:
df.duplicated().sum()

np.int64(0)

In [61]:
df.dtypes

id                           int64
timestamp           datetime64[ns]
redemption_count             int64
sales_count                  int64
hours                        int64
day_name            string[python]
month_name          string[python]
month                        int64
season              string[python]
week_part           string[python]
gap                          int64
dtype: object

In [46]:
df[['hours','month']] = df[['hours','month']].astype('int64')

In [48]:
df[['day_name','month_name','season','week_part']] = df[['day_name','month_name','season','week_part']].astype('string')

# Now let's convert dataframe into my sql server database

In [5]:
engine = create_engine('mysql+pymysql://root:qwe99ewq@localhost/island_db')

In [55]:
with engine.connect() as conn:
    result = conn.execute(text('SHOW DATABASES'))
for i in result:
    print(i)

('amazon_db',)
('coffee_roasters_db',)
('customers_db',)
('harryshop',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

# Create a database

In [56]:
with engine.connect() as conn:
    conn.execute(text('CREATE DATABASE island_db'))

In [57]:
with engine.connect() as conn:
    result = conn.execute(text('SHOW DATABASES'))
for i in result:
    print(i)

('amazon_db',)
('coffee_roasters_db',)
('customers_db',)
('harryshop',)
('information_schema',)
('island_db',)
('mysql',)
('performance_schema',)
('sys',)

In [60]:
df.head(1)

,id,timestamp,redemption_count,sales_count,hours,day_name,month_name,month,season,week_part,gap
0,1,2025-12-21 22:30:00,14,16,22,Sunday,December,12,Winter,Weekend,2

In [66]:
df.to_sql('ticket_trackingdata',con=engine,index=False,if_exists='replace')

261538

# ===============================================================================================================================================